import{a as P,S as M,i as d}from"./assets/vendor-C1DvvBV_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const u of a.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const v="57834009-e331d273ed5c63387cc2a8569",y=15;async function h(r,t){return await P("https://pixabay.com/api/",{params:{key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:y,page:t}}).then(({data:o})=>o)}const S=new M(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}),i={form:document.querySelector(".form"),loader:document.querySelector(".loader"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-more")};function g(r){const t=r.map(({webformatURL:o,largeImageURL:s,tags:e,likes:a,views:u,comments:w,downloads:b})=>`
        <li class="gallery-item">
            <a class="gallery-item-link" href="${s}"><img src="${o}" alt="${e}"></a>
            <ul class="gallery-img-info">
              <li class="gallery-info-item">Likes <span>${a}</span></li>
              <li class="gallery-info-item">Views <span>${u}</span></li>
              <li class="gallery-info-item">Comments <span>${w}</span></li>
              <li class="gallery-info-item">Downloads <span>${b}</span></li>
            </ul>
        </li>
        `).join("");i.gallery.insertAdjacentHTML("beforeend",t),S.refresh()}function B(){i.gallery.innerHTML=""}function p(){i.loader.classList.add("show")}function L(){i.loader.classList.remove("show")}function m(){i.loadMoreBtn.classList.add("is-shown")}function f(){i.loadMoreBtn.classList.remove("is-shown")}i.form.addEventListener("submit",$);i.loadMoreBtn.addEventListener("click",q);let l=1,n="";async function $(r){if(r.preventDefault(),n=r.currentTarget.elements["search-text"].value.trim(),!!n){f(),B(),p(),l=1;try{const{hits:t,totalHits:o}=await h(n,l),s=Math.ceil(o/y);t.length>0?(g(t),l===s?(c("We're sorry, but you've reached the end of search results.","info"),f()):m()):c(`Sorry, there are no images matching your ${n}. Please try again!`,"error")}catch(t){c(t,"error")}finally{L()}}}async function q(){if(n!==""){l+=1,f(),p();try{const{hits:r,totalHits:t}=await h(n,l),o=Math.ceil(t/y);if(r.length>0){g(r);const s=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"}),l===o?(c("We're sorry, but you've reached the end of search results.","info"),f()):m()}else c(`Sorry, there are no images matching your ${n}. Please try again!`,"error")}catch(r){c(r,"error"),m()}finally{L()}}}function c(r,t="success"){const o={message:r,position:"topRight",timeout:5e3};switch(t){case"success":d.success(o);break;case"error":d.error(o);break;case"warning":d.warning(o);break;case"info":d.info(o);break;default:d.error({message:"Invalid Type Of toast",position:"topRight",timeout:5e3})}}
//# sourceMappingURL=index.js.map
